spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/show-doc?serverTimezone=PRC&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  mapper-locations: mapper/*Mapper.xml

logging:
  level:
    com.tianyisoft.showdoc.mapper: debug
    # org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
